FROM --platform=linux/amd64 golang:1.20.5

WORKDIR /app/indexer

COPY app/indexer/go.mod app/indexer/go.sum ./

RUN go mod download

COPY ./app/indexer/ ./

# CMD ["air", "-c", ".air.toml"]
CMD ["go", "run", "."]