# YAML file for Github Actions to use to build the Docker Image
name: Github Actions Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker Compose
        run: docker-compose build